# Conclusion

The mean tuition increases over 2017 to 2021. This could either indicate that the impact that covid imposed on the education industry or merely demonstrate the cost of education is increasing over years. We also show the fact from the QS ranking vs mean earning plot & tuition plot that students graduated from universities with high ranking usually have more earning.

Based on the observation from admission, it can be concluded that the pandemic may have had an influence on the number and rate of admissions at different types of institutions. The total number of admissions at public and private nonprofit institutions increased from 2017 to 2021, while the total number of admissions at private for-profit institutions decreased in 2021. The admission rate was found to be higher at private for-profit institutions compared to private nonprofit and public institutions. 

The admission rate for private nonprofit and public institutions increased over the years, particularly in 2021, while the admission rate for private for-profit institutions fluctuated. Gender was found to be a factor in the admission rate, with women having a higher chance of being admitted at public and private nonprofit institutions compared to men. 

The mean SAT scores for admitted students were higher for verbal scores compared to math scores, and the standard for admission appeared to be higher at private nonprofit institutions compared to public institutions. The standard for private for-profit institutions had a large variance in different years.

The histogram of percentage of institutional grant receiver faceting over different institutions indicates that the pattern of distributing institutional grant for all types of institutions does not change during the pandemics. The difference in percentage of grant receivers between different types of institutions is related to how the institutions are financed. 

Institutional grant increases significantly around the great lake area but decreases around the west part of the midwest and south states. This polarizing phenomenon is a good metric to evaluate economic prowess of institutions in different regions as only well financed institutions would be willing and able to raise the amount of grants to students suffering from financial difficulties due to the pandemics.

During the pandemics, there is an increasing number of “Female Majority” institutions. Though a rise in enrollment and admission of female students has been observed before the pandemics, the drastic decrease in number of “Neutral” institutions is worth noting. As discovered in “admission” analysis, females generally have a higher rate of admission than male. It is possible that there are more Female Majority institutions due to higher chances of female applicants. 

There has been very minor fluctuation of racial diversity in US institutions in each state. The team initially presumed that racial demographics would be impacted significantly as the team assumed that racial minority groups are financially vulnerable, making their education difficult due to high tuition of US institutions during economic recession due to the pandemic. However, the change in racial diversity is not as prominent as observed in gender diversity. 

Overall, the pandemics lowered the bar of college admission in terms of admission rate and test score for for profit institutions. The pandemics could have compelled for profit private schools to admit more students for financial gain. However, the admission rate also increases for public institutions. There has been little to no racial diversity fluctuation, which means pandemics do not impact education opportunities of racial minorities as much as the team expected. The availability of institutional grants, rather than increase or decrease among all states, shows high regional variation. Non profit institutions are more likely to provide aid than public and for profit institutions.  Institutions in some regions are more willing and able to provide institutional aid then institutions in other regions. 

The exploration also revealed future directions. What accounts for regional differences in the change of institutional grants in different regions? Is the high chance of admission for females accountable for the increasing number of “Female Majority” institutions in the US? The admission rate for both public and nonprofit private institutions increases over the pandemics. Is this because institutions are more willing to provide education opportunities or the number of applicants drops due to financial difficulties? Should there be more data involving student outcome (earning) of graduated students, the team would have performed more through analysis on the benefit of college education in the difficult time of pandemics. 

A major takeaway for team members from this project is a deeper insight in the reliability of data sources. The team member opted to use the IPEDS data set because the team expected high data availability from government sourced data. However, the team did not expect that the purpose of data collection– monitoring institutions receiving federal funds– would have a profound impact on data availability. Many for-profit private institutions did not provide any data at all because they did not receive federal funding. Many education institutions in the US are more like private business rather than public welfare  oriented institutions, who would not reveal crucial performance metric when they are not obligated to. The lack of cooperation from those institutions severely compromised availability of data, indicating that the team has overestimated the authority of the government in data collection. The team members would pay more attention to the benefit relationship between data collector and providers before concluding the reliability of the dataset. 
