# Proposal

## Research topic

The outbreaks of covid-19 have had a big impact on all walks of life since 2019. For many college applicants and their families, one of the topics they care about most is whether, and if so how, the pandemics affect admissions and their future developments after graduation. With reference to college rankings, applicants can get “easy-to-interpret” information about a college. However, that information is limited, and there is something that applicants are really concerned about but can not be captured by the college rankings, such as the admission conditions and average graduate salaries.

In this project, we aim to help applicants figure out the trends under the pandemic and support them to make well-formulated decisions that maximize their utility from education at this particular time. To reach this goal, we will combine the information on college rankings, college type, admission conditions, tuition fees, average graduate salaries, and so on, to analyze their relationships as well as variations before and after the pandemics.

## Data availability

